version: 2.1

build-images: &build-images
  parameters:
    publish:
      type: boolean
      default: false
    versions:
      type: string
      default: ""
  machine: true
  steps:
    - checkout
    - when:
        condition: << parameters.versions >>
        steps:
          - run:
              name: Setup custom environment variables
              command: echo 'export VERSIONS=<< parameters.versions >>' >> $BASH_ENV
    - run:
        name: Build images
        command: make build-all
    - run:
        name: Test images
        command: make test-all
    - when:
        condition: << parameters.publish >>
        steps:
          - run:
              name: Docker login
              command: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          - run:
              name: Publish images
              command: make push-all

branch-master: &branch-master
  publish: true
  filters:
    branches:
      only: master

branch-default: &branch-default
  publish: false
  filters:
    branches:
      ignore: master

r-devel: &r-devel
  publish: true
  versions: devel

jobs:
  xenial:
    <<: *build-images
    environment:
      VARIANTS: xenial
  bionic:
    <<: *build-images
    environment:
      VARIANTS: bionic
  focal:
    <<: *build-images
    environment:
      VARIANTS: focal
  centos6:
    <<: *build-images
    environment:
      VARIANTS: centos6
  centos7:
    <<: *build-images
    environment:
      VARIANTS: centos7
  centos8:
    <<: *build-images
    environment:
      VARIANTS: centos8
  opensuse42:
    <<: *build-images
    environment:
      VARIANTS: opensuse42
  opensuse15:
    <<: *build-images
    environment:
      VARIANTS: opensuse15
  opensuse152:
    <<: *build-images
    environment:
      VARIANTS: opensuse152


workflows:
  version: 2
  build-default:
    jobs:
      - xenial:
          <<: *branch-default
      - bionic:
          <<: *branch-default
      - focal:
          <<: *branch-default
      - centos6:
          <<: *branch-default
      - centos7:
          <<: *branch-default
      - centos8:
          <<: *branch-default
      - opensuse42:
          <<: *branch-default
      - opensuse15:
          <<: *branch-default
      - opensuse152:
          <<: *branch-default
  build-master:
    jobs:
      - xenial:
          <<: *branch-master
      - bionic:
          <<: *branch-master
      - focal:
          <<: *branch-master
      - centos6:
          <<: *branch-master
      - centos7:
          <<: *branch-master
      - centos8:
          <<: *branch-master
      - opensuse42:
          <<: *branch-master
      - opensuse15:
          <<: *branch-master
      - opensuse152:
          <<: *branch-master
  build-r-devel-daily:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - xenial:
          <<: *r-devel
      - bionic:
          <<: *r-devel
      - focal:
          <<: *r-devel
      - centos6:
          <<: *r-devel
      - centos7:
          <<: *r-devel
      - centos8:
          <<: *r-devel
      - opensuse42:
          <<: *r-devel
      - opensuse15:
          <<: *r-devel
      - opensuse152:
          <<: *r-devel
